### ISSUE TITLE
[Help] addResponseFilter

### ISSUE THREAD

**Issue by Frankusky** [jmangs/node-browsermob-proxy-api#11]
Im trying to apply a mocked response with addResponseFilter but I dont know what value should go in js parameter:
```
addResponseFilter: function(port, js, callback) {
        this._post('/proxy/' + port + '/filter/response', js, JAVASCRIPT_MIME, callback);
    },
```

PS: sorry for creating an issue, but there is no documentation

**Comment by jmangs** [comment]
The documentation is on `browser-mob-proxy`'s repository:

[(LittleProxy) interceptors](https://github.com/lightbody/browsermob-proxy/blob/master/README.md#210-littleproxy-interceptors)
[Legacy Interceptors](https://github.com/lightbody/browsermob-proxy/blob/master/README.md#legacy-interceptors)

From the legacy section, it states that the JS code run by the proxy is the same as the Java API examples given. You will need to track down the Java API docs from their repository; I'm not very familiar with them myself:

>You can also POST a JavaScript payload to /:port/interceptor/request and /:port/interceptor/response using the REST interface. The functions will have a request/response variable, respectively, and a har variable (which may be null if a HAR isn't set up yet). The JavaScript code will be run by Rhino and have access to the same Java API in the example above:
>```
>[~]$ curl -X POST -H 'Content-Type: text/plain' -d 'request.getMethod().removeHeaders("User-Agent");' http://localhost:8080/proxy/8081/interceptor/request
>```
>Consult the Java API docs for more info.
