### ISSUE TITLE
Content-Length for unicode characters

### ISSUE THREAD

**Issue by NelsonChang** [jmangs/node-browsermob-proxy-api#9]
When I use 'filter/response' to POST, it returns 500 Error on the browsermob-proxy.
I looked into the issue, and I think it's the content-Length is incorrect when the test data has unicode characters. 

Sample code:
var testData = [
    {
        "test": "汉字"
    }
];
var  str= "if(messageInfo.getOriginalUrl().endsWith('api/')){contents.setTextContents("+JSON.stringify(testData)+");}";

proxy.addResponseFilter(proxy_params.port, str, bar);

When I remove "Content-Length", it returns 200 immediately.

**Comment by jmangs** [comment]
This should be fixed in `0.4.0`; it was not calculating the proper byte length of the string (multi-byte characters specifically). New version should be uploaded later today.
